device: warboy(2)*1
output_dir: /users/chanmin/3D_Unet/pytorch-3dunet/npu_pipeline/examples/confocal_boundary/output
patch_config:
  batch_size: 1
  halo_shape:
  - 16
  - 32
  - 32
  patch_shape:
  - 80
  - 170
  - 170
  stride_shape:
  - 80
  - 170
  - 170
results:
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''u'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: u
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''s'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: s
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''e'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: e
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''r'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: r
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''s'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: s
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''c'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: c
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''h'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: h
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''a'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: a
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''n'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: n
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''m'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: m
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''i'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: i
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''n'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: n
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''3'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: '3'
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''D'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: D
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''_'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: _
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''U'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: U
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''n'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: n
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''e'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: e
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''t'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: t
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''p'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: p
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''y'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: y
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''t'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: t
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''o'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: o
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''r'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: r
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''c'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: c
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''h'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: h
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''-'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: '-'
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''3'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: '3'
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''d'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: d
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''u'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: u
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''n'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: n
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''e'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: e
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''t'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: t
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''n'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: n
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''p'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: p
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''u'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: u
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''_'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: _
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''p'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: p
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''i'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: i
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''p'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: p
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''e'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: e
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''l'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: l
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''i'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: i
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''n'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: n
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''e'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: e
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''e'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: e
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''x'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: x
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''a'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: a
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''m'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: m
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''p'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: p
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''l'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: l
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''e'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: e
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''s'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: s
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''c'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: c
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''o'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: o
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''n'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: n
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''f'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: f
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''o'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: o
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''c'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: c
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''a'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: a
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''l'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: l
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''_'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: _
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''b'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: b
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''o'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: o
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''u'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: u
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''n'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: n
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''d'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: d
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''a'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: a
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''r'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: r
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''y'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: y
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''d'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: d
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''a'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: a
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''t'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: t
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''a'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: a
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''s'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: s
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''e'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: e
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''t'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: t
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''t'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: t
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''e'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: e
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''s'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: s
- error: '[Errno 2] Unable to synchronously open file (unable to open file: name =
    ''t'', errno = 2, error message = ''No such file or directory'', flags = 0, o_flags
    = 0)'
  file_path: t
total_files: 81
